"""PostUpdated_AddedOuterServiceId

Revision ID: 026373a2a540
Revises: 3ad7cb38b47e
Create Date: 2024-11-29 09:48:07.446235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026373a2a540'
down_revision: Union[str, None] = '3ad7cb38b47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('outer_service_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'outer_service_id')
    # ### end Alembic commands ###
