"""Comment_Updated_ParentId_Nullable

Revision ID: 3ad7cb38b47e
Revises: bd2dcc115ebf
Create Date: 2024-11-20 15:29:50.233735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad7cb38b47e'
down_revision: Union[str, None] = 'bd2dcc115ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'parent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'parent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
