"""update_posts_set_nullable_fields

Revision ID: 6865d7e2633e
Revises: 6da57b0f260e
Create Date: 2024-11-18 13:04:37.551307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6865d7e2633e'
down_revision: Union[str, None] = '6da57b0f260e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'publisher_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'link_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'link_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'geo_tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'geo_tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'link_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'link_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'publisher_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
