"""Posts_Updated_Added_UserID

Revision ID: 6da57b0f260e
Revises: b474e410dec4
Create Date: 2024-11-11 11:41:44.138185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da57b0f260e'
down_revision: Union[str, None] = 'b474e410dec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
